# Generated by Django 2.1.4 on 2018-12-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('base_price', models.PositiveIntegerField(default=0)),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
