# Generated by Django 2.1.4 on 2019-01-04 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='short_description',
            field=models.TextField(default='Salaaaaaaaaam', help_text='Enter a brief description of your item to '
                                                                      'showin the auctions list', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='base_price',
            field=models.PositiveIntegerField(default=10000, help_text='Base price in Tomans'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(verbose_name='Finish date'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(help_text='Enter a more detailed description of your item', max_length=1000),
        ),
        migrations.AlterField(
            model_name='auction',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Publication date'),
        ),
    ]
