# Generated by Django 2.1.4 on 2019-01-15 06:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 6, 34, 59, 825261, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
