# Generated by Django 2.1.4 on 2019-01-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190115_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
