# Generated by Django 2.1.4 on 2019-02-01 19:29

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190201_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=core.models.get_image_filename, validators=[core.models.auction_picture_validator])),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Auction')),
            ],
        ),
    ]
