# Generated by Django 2.1.4 on 2019-02-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auction_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='state',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'approved'), (2, 'rejected')], default=0),
        ),
    ]
