# Generated by Django 2.1.4 on 2019-02-04 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190131_2219'),
        ('core', '0012_auto_20190204_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Please specify the reason.', max_length=200)),
                ('date', models.DateTimeField()),
                ('reported_auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Auction')),
                ('reporter_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
            ],
        ),
    ]
