# Generated by Django 2.1.4 on 2019-02-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
