# Generated by Django 2.1.4 on 2019-02-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_report_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='state',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'approved'), (2, 'rejected'), (3, 'suspended')], default=0),
        ),
    ]
