language: python
python:
  - "3.6"
services:
  - rabbitmq
  - postgresql
env:
  -DJANGO=2.1 DB=postgresql
install:
  - pip install -r requirements/development.txt
before_script:
  - python manage.py migrate
script:
  - python manage.py test
