# Generated by Django 2.1.4 on 2019-01-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190115_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reserved_credit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
